// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: accounts.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, email, password_hash, allowed_domains, api_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, password_hash, allowed_domains, api_key, created_at, updated_at, tenant_id
`

type CreateAccountParams struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	PasswordHash   string `json:"password_hash"`
	AllowedDomains []byte `json:"allowed_domains"`
	ApiKey         string `json:"api_key"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.AllowedDomains,
		arg.ApiKey,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.AllowedDomains,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByAPIKey = `-- name: GetAccountByAPIKey :one
SELECT id, name, email, password_hash, allowed_domains, api_key, created_at, updated_at, tenant_id FROM accounts WHERE api_key = $1
`

func (q *Queries) GetAccountByAPIKey(ctx context.Context, apiKey string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByAPIKey, apiKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.AllowedDomains,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, email, password_hash, allowed_domains, api_key, created_at, updated_at, tenant_id FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.AllowedDomains,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getAccountByName = `-- name: GetAccountByName :one
SELECT id, name, email, password_hash, allowed_domains, api_key, created_at, updated_at, tenant_id FROM accounts WHERE name = $1
`

func (q *Queries) GetAccountByName(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByName, name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.AllowedDomains,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, email, password_hash, allowed_domains, api_key, created_at, updated_at, tenant_id FROM accounts ORDER BY created_at DESC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.AllowedDomains,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, email = $3, allowed_domains = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password_hash, allowed_domains, api_key, created_at, updated_at, tenant_id
`

type UpdateAccountParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	AllowedDomains []byte    `json:"allowed_domains"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AllowedDomains,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.AllowedDomains,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
