// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIKeysByUserID = `-- name: CountAPIKeysByUserID :one
SELECT COUNT(*)::integer FROM api_keys WHERE user_id = $1 AND is_active = true
`

func (q *Queries) CountAPIKeysByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAPIKeysByUserID, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_prefix, key_hash, label, expires_at, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, key_prefix, key_hash, label, is_active, expires_at, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	KeyPrefix string             `json:"key_prefix"`
	KeyHash   string             `json:"key_hash"`
	Label     string             `json:"label"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  bool               `json:"is_active"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Label,
		arg.ExpiresAt,
		arg.IsActive,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Label,
		&i.IsActive,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const deleteAllAPIKeysByUserID = `-- name: DeleteAllAPIKeysByUserID :exec
DELETE FROM api_keys WHERE user_id = $1
`

func (q *Queries) DeleteAllAPIKeysByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllAPIKeysByUserID, userID)
	return err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, user_id, key_prefix, key_hash, label, is_active, expires_at, last_used_at, created_at FROM api_keys
WHERE key_prefix = $1 AND is_active = true
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Label,
		&i.IsActive,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
SELECT id, user_id, key_prefix, label, is_active, expires_at, last_used_at, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByUserIDRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	KeyPrefix  string             `json:"key_prefix"`
	Label      string             `json:"label"`
	IsActive   bool               `json:"is_active"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByUserIDRow
	for rows.Next() {
		var i ListAPIKeysByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyPrefix,
			&i.Label,
			&i.IsActive,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateAPIKeyStatus = `-- name: UpdateAPIKeyStatus :one
UPDATE api_keys SET is_active = $3 WHERE id = $1 AND user_id = $2
RETURNING id, user_id, key_prefix, key_hash, label, is_active, expires_at, last_used_at, created_at
`

type UpdateAPIKeyStatusParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateAPIKeyStatus(ctx context.Context, arg UpdateAPIKeyStatusParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKeyStatus, arg.ID, arg.UserID, arg.IsActive)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Label,
		&i.IsActive,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}
