// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// AuditLog represents a row in the audit_logs table.
type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Result       string             `json:"result"`
	Metadata     []byte             `json:"metadata"`
	IPAddress    pgtype.Text        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (tenant_id, user_id, action, resource_type, resource_id, result, metadata, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, user_id, action, resource_type, resource_id, result, metadata, ip_address, created_at
`

type CreateAuditLogParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	UserID       pgtype.UUID `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Result       string      `json:"result"`
	Metadata     []byte      `json:"metadata"`
	IPAddress    pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TenantID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.Metadata,
		arg.IPAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Result,
		&i.Metadata,
		&i.IPAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByTenantID = `-- name: ListAuditLogsByTenantID :many
SELECT id, tenant_id, user_id, action, resource_type, resource_id, result, metadata, ip_address, created_at FROM audit_logs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByTenantIDParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAuditLogsByTenantID(ctx context.Context, arg ListAuditLogsByTenantIDParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTenantID, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Result,
			&i.Metadata,
			&i.IPAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
