// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_logs.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryLog = `-- name: CreateDeliveryLog :one
INSERT INTO delivery_logs (message_id, provider_id, status, response_code, response_body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, message_id, provider_id, status, response_code, response_body, delivered_at
`

type CreateDeliveryLogParams struct {
	MessageID    uuid.UUID   `json:"message_id"`
	ProviderID   uuid.UUID   `json:"provider_id"`
	Status       string      `json:"status"`
	ResponseCode pgtype.Int4 `json:"response_code"`
	ResponseBody pgtype.Text `json:"response_body"`
}

func (q *Queries) CreateDeliveryLog(ctx context.Context, arg CreateDeliveryLogParams) (DeliveryLog, error) {
	row := q.db.QueryRow(ctx, createDeliveryLog,
		arg.MessageID,
		arg.ProviderID,
		arg.Status,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	var i DeliveryLog
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ProviderID,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.DeliveredAt,
	)
	return i, err
}

const listDeliveryLogsByMessageID = `-- name: ListDeliveryLogsByMessageID :many
SELECT id, message_id, provider_id, status, response_code, response_body, delivered_at FROM delivery_logs WHERE message_id = $1 ORDER BY delivered_at DESC
`

func (q *Queries) ListDeliveryLogsByMessageID(ctx context.Context, messageID uuid.UUID) ([]DeliveryLog, error) {
	rows, err := q.db.Query(ctx, listDeliveryLogsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryLog
	for rows.Next() {
		var i DeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProviderID,
			&i.Status,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
