// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain_rate_limits.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createDomainRateLimit = `-- name: CreateDomainRateLimit :one
INSERT INTO domain_rate_limits (group_id, domain, max_per_minute, max_per_hour, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_id, domain, max_per_minute, max_per_hour, enabled, created_at, updated_at
`

type CreateDomainRateLimitParams struct {
	GroupID      uuid.UUID `json:"group_id"`
	Domain       string    `json:"domain"`
	MaxPerMinute int32     `json:"max_per_minute"`
	MaxPerHour   int32     `json:"max_per_hour"`
	Enabled      bool      `json:"enabled"`
}

func (q *Queries) CreateDomainRateLimit(ctx context.Context, arg CreateDomainRateLimitParams) (DomainRateLimit, error) {
	row := q.db.QueryRow(ctx, createDomainRateLimit,
		arg.GroupID,
		arg.Domain,
		arg.MaxPerMinute,
		arg.MaxPerHour,
		arg.Enabled,
	)
	var i DomainRateLimit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Domain,
		&i.MaxPerMinute,
		&i.MaxPerHour,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomainRateLimit = `-- name: DeleteDomainRateLimit :exec
DELETE FROM domain_rate_limits WHERE id = $1
`

func (q *Queries) DeleteDomainRateLimit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDomainRateLimit, id)
	return err
}

const getDomainRateLimit = `-- name: GetDomainRateLimit :one
SELECT id, group_id, domain, max_per_minute, max_per_hour, enabled, created_at, updated_at FROM domain_rate_limits
WHERE group_id = $1 AND domain = $2
`

type GetDomainRateLimitParams struct {
	GroupID uuid.UUID `json:"group_id"`
	Domain  string    `json:"domain"`
}

func (q *Queries) GetDomainRateLimit(ctx context.Context, arg GetDomainRateLimitParams) (DomainRateLimit, error) {
	row := q.db.QueryRow(ctx, getDomainRateLimit, arg.GroupID, arg.Domain)
	var i DomainRateLimit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Domain,
		&i.MaxPerMinute,
		&i.MaxPerHour,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomainRateLimitsByGroupID = `-- name: ListDomainRateLimitsByGroupID :many
SELECT id, group_id, domain, max_per_minute, max_per_hour, enabled, created_at, updated_at FROM domain_rate_limits
WHERE group_id = $1
ORDER BY domain ASC
`

func (q *Queries) ListDomainRateLimitsByGroupID(ctx context.Context, groupID uuid.UUID) ([]DomainRateLimit, error) {
	rows, err := q.db.Query(ctx, listDomainRateLimitsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainRateLimit
	for rows.Next() {
		var i DomainRateLimit
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Domain,
			&i.MaxPerMinute,
			&i.MaxPerHour,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomainRateLimit = `-- name: UpdateDomainRateLimit :one
UPDATE domain_rate_limits
SET max_per_minute = $2, max_per_hour = $3, enabled = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, domain, max_per_minute, max_per_hour, enabled, created_at, updated_at
`

type UpdateDomainRateLimitParams struct {
	ID           uuid.UUID `json:"id"`
	MaxPerMinute int32     `json:"max_per_minute"`
	MaxPerHour   int32     `json:"max_per_hour"`
	Enabled      bool      `json:"enabled"`
}

func (q *Queries) UpdateDomainRateLimit(ctx context.Context, arg UpdateDomainRateLimitParams) (DomainRateLimit, error) {
	row := q.db.QueryRow(ctx, updateDomainRateLimit,
		arg.ID,
		arg.MaxPerMinute,
		arg.MaxPerHour,
		arg.Enabled,
	)
	var i DomainRateLimit
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Domain,
		&i.MaxPerMinute,
		&i.MaxPerHour,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
