// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, group_type, display_name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type, group_key, display_name, description
`

type CreateGroupParams struct {
	Name        string         `json:"name"`
	GroupType   string         `json:"group_type"`
	DisplayName sql.NullString `json:"display_name"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.GroupType,
		arg.DisplayName,
		arg.Description,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
		&i.GroupKey,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByGroupKey = `-- name: GetGroupByGroupKey :one
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type, group_key, display_name, description FROM groups WHERE group_key = $1
`

func (q *Queries) GetGroupByGroupKey(ctx context.Context, groupKey uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByGroupKey, groupKey)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
		&i.GroupKey,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type, group_key, display_name, description FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
		&i.GroupKey,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type, group_key, display_name, description FROM groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
		&i.GroupKey,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}

const incrementMonthlySent = `-- name: IncrementMonthlySent :exec
UPDATE groups
SET monthly_sent = monthly_sent + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementMonthlySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMonthlySent, id)
	return err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type, group_key, display_name, description FROM groups WHERE status != 'deleted' ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.MonthlyLimit,
			&i.MonthlySent,
			&i.AllowedIps,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupType,
			&i.GroupKey,
			&i.DisplayName,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMonthlySent = `-- name: ResetMonthlySent :exec
UPDATE groups
SET monthly_sent = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetMonthlySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetMonthlySent, id)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2, status = $3, monthly_limit = $4, display_name = $5, description = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type, group_key, display_name, description
`

type UpdateGroupParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Status       string         `json:"status"`
	MonthlyLimit int32          `json:"monthly_limit"`
	DisplayName  sql.NullString `json:"display_name"`
	Description  pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.MonthlyLimit,
		arg.DisplayName,
		arg.Description,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
		&i.GroupKey,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}

const updateGroupStatus = `-- name: UpdateGroupStatus :one
UPDATE groups
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type, group_key, display_name, description
`

type UpdateGroupStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateGroupStatus(ctx context.Context, arg UpdateGroupStatusParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupStatus, arg.ID, arg.Status)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
		&i.GroupKey,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}
