// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, group_type)
VALUES ($1, $2)
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type
`

type CreateGroupParams struct {
	Name      string `json:"name"`
	GroupType string `json:"group_type"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.GroupType)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type FROM groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
	)
	return i, err
}

const incrementMonthlySent = `-- name: IncrementMonthlySent :exec
UPDATE groups
SET monthly_sent = monthly_sent + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementMonthlySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMonthlySent, id)
	return err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type FROM groups ORDER BY created_at DESC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.MonthlyLimit,
			&i.MonthlySent,
			&i.AllowedIps,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMonthlySent = `-- name: ResetMonthlySent :exec
UPDATE groups
SET monthly_sent = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetMonthlySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetMonthlySent, id)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2, status = $3, monthly_limit = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type
`

type UpdateGroupParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Status       string    `json:"status"`
	MonthlyLimit int32     `json:"monthly_limit"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.MonthlyLimit,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
	)
	return i, err
}

const updateGroupStatus = `-- name: UpdateGroupStatus :one
UPDATE groups
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at, group_type
`

type UpdateGroupStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateGroupStatus(ctx context.Context, arg UpdateGroupStatusParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupStatus, arg.ID, arg.Status)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupType,
	)
	return i, err
}
