// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_members.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const countGroupOwners = `-- name: CountGroupOwners :one
SELECT count(*) FROM group_members WHERE group_id = $1 AND role = 'owner'
`

func (q *Queries) CountGroupOwners(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupOwners, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, group_id, user_id, role, created_at
`

type CreateGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember, arg.GroupID, arg.UserID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM group_members WHERE id = $1
`

func (q *Queries) DeleteGroupMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, id)
	return err
}

const deleteGroupMembersByUserID = `-- name: DeleteGroupMembersByUserID :exec
DELETE FROM group_members WHERE user_id = $1
`

func (q *Queries) DeleteGroupMembersByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupMembersByUserID, userID)
	return err
}

const getGroupMemberByID = `-- name: GetGroupMemberByID :one
SELECT id, group_id, user_id, role, created_at FROM group_members WHERE id = $1
`

func (q *Queries) GetGroupMemberByID(ctx context.Context, id uuid.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByID, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMemberByUserAndGroup = `-- name: GetGroupMemberByUserAndGroup :one
SELECT id, group_id, user_id, role, created_at FROM group_members WHERE user_id = $1 AND group_id = $2
`

type GetGroupMemberByUserAndGroupParams struct {
	UserID  uuid.UUID `json:"user_id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) GetGroupMemberByUserAndGroup(ctx context.Context, arg GetGroupMemberByUserAndGroupParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByUserAndGroup, arg.UserID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listGroupMembersByGroupID = `-- name: ListGroupMembersByGroupID :many
SELECT id, group_id, user_id, role, created_at FROM group_members WHERE group_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGroupMembersByGroupID(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembersByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByUserID = `-- name: ListGroupsByUserID :many
SELECT g.id, g.name, g.status, g.monthly_limit, g.monthly_sent, g.allowed_ips, g.created_at, g.updated_at, g.group_type FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY gm.created_at ASC
`

func (q *Queries) ListGroupsByUserID(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.MonthlyLimit,
			&i.MonthlySent,
			&i.AllowedIps,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :one
UPDATE group_members
SET role = $2
WHERE id = $1
RETURNING id, group_id, user_id, role, created_at
`

type UpdateGroupMemberRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberRole, arg.ID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
