// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const enqueueMessage = `-- name: EnqueueMessage :one
INSERT INTO messages (account_id, sender, recipients, subject, headers, body, status)
VALUES ($1, $2, $3, $4, $5, $6, 'queued')
RETURNING id, account_id, sender, recipients, subject, headers, body, status, provider_id, enqueued_at, processed_at
`

type EnqueueMessageParams struct {
	AccountID  uuid.UUID      `json:"account_id"`
	Sender     string         `json:"sender"`
	Recipients []byte         `json:"recipients"`
	Subject    sql.NullString `json:"subject"`
	Headers    []byte         `json:"headers"`
	Body       string         `json:"body"`
}

func (q *Queries) EnqueueMessage(ctx context.Context, arg EnqueueMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, enqueueMessage,
		arg.AccountID,
		arg.Sender,
		arg.Recipients,
		arg.Subject,
		arg.Headers,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Sender,
		&i.Recipients,
		&i.Subject,
		&i.Headers,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.EnqueuedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, account_id, sender, recipients, subject, headers, body, status, provider_id, enqueued_at, processed_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Sender,
		&i.Recipients,
		&i.Subject,
		&i.Headers,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.EnqueuedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getQueuedMessages = `-- name: GetQueuedMessages :many
SELECT id, account_id, sender, recipients, subject, headers, body, status, provider_id, enqueued_at, processed_at FROM messages WHERE status = 'queued' ORDER BY enqueued_at ASC LIMIT $1
`

func (q *Queries) GetQueuedMessages(ctx context.Context, limit int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getQueuedMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Sender,
			&i.Recipients,
			&i.Subject,
			&i.Headers,
			&i.Body,
			&i.Status,
			&i.ProviderID,
			&i.EnqueuedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByAccountID = `-- name: ListMessagesByAccountID :many
SELECT id, account_id, sender, recipients, subject, headers, body, status, provider_id, enqueued_at, processed_at FROM messages WHERE account_id = $1 ORDER BY enqueued_at DESC LIMIT $2
`

type ListMessagesByAccountIDParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListMessagesByAccountID(ctx context.Context, arg ListMessagesByAccountIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByAccountID, arg.AccountID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Sender,
			&i.Recipients,
			&i.Subject,
			&i.Headers,
			&i.Body,
			&i.Status,
			&i.ProviderID,
			&i.EnqueuedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE messages SET status = $2, processed_at = NOW() WHERE id = $1
`

type UpdateMessageStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status MessageStatus `json:"status"`
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatus, arg.ID, arg.Status)
	return err
}
