// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryStatus string

const (
	DeliveryStatusPending    DeliveryStatus = "pending"
	DeliveryStatusQueued     DeliveryStatus = "queued"
	DeliveryStatusProcessing DeliveryStatus = "processing"
	DeliveryStatusSent       DeliveryStatus = "sent"
	DeliveryStatusFailed     DeliveryStatus = "failed"
	DeliveryStatusBounced    DeliveryStatus = "bounced"
	DeliveryStatusComplained DeliveryStatus = "complained"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type MessageStatus string

const (
	MessageStatusQueued     MessageStatus = "queued"
	MessageStatusProcessing MessageStatus = "processing"
	MessageStatusDelivered  MessageStatus = "delivered"
	MessageStatusFailed     MessageStatus = "failed"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus `json:"message_status"`
	Valid         bool          `json:"valid"` // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type ProviderType string

const (
	ProviderTypeSendgrid ProviderType = "sendgrid"
	ProviderTypeMailgun  ProviderType = "mailgun"
	ProviderTypeSes      ProviderType = "ses"
	ProviderTypeSmtp     ProviderType = "smtp"
	ProviderTypeMsgraph  ProviderType = "msgraph"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType `json:"provider_type"`
	Valid        bool         `json:"valid"` // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type Account struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	AllowedDomains []byte             `json:"allowed_domains"`
	ApiKey         string             `json:"api_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryLog struct {
	ID                uuid.UUID          `json:"id"`
	MessageID         uuid.UUID          `json:"message_id"`
	ProviderID        uuid.UUID          `json:"provider_id"`
	Status            string             `json:"status"`
	ResponseCode      pgtype.Int4        `json:"response_code"`
	ResponseBody      pgtype.Text        `json:"response_body"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	TenantID          sql.NullString     `json:"tenant_id"`
	Provider          sql.NullString     `json:"provider"`
	ProviderMessageID sql.NullString     `json:"provider_message_id"`
	RetryCount        int32              `json:"retry_count"`
	LastError         pgtype.Text        `json:"last_error"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EspProvider struct {
	ID           uuid.UUID          `json:"id"`
	AccountID    uuid.UUID          `json:"account_id"`
	Name         string             `json:"name"`
	ProviderType ProviderType       `json:"provider_type"`
	ApiKey       sql.NullString     `json:"api_key"`
	SmtpConfig   []byte             `json:"smtp_config"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	Sender      string             `json:"sender"`
	Recipients  []byte             `json:"recipients"`
	Subject     sql.NullString     `json:"subject"`
	Headers     []byte             `json:"headers"`
	Body        string             `json:"body"`
	Status      MessageStatus      `json:"status"`
	ProviderID  pgtype.UUID        `json:"provider_id"`
	EnqueuedAt  pgtype.Timestamptz `json:"enqueued_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type RoutingRule struct {
	ID         uuid.UUID          `json:"id"`
	AccountID  uuid.UUID          `json:"account_id"`
	Priority   int32              `json:"priority"`
	Conditions []byte             `json:"conditions"`
	ProviderID uuid.UUID          `json:"provider_id"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
