// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_fallbacks.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderFallback = `-- name: CreateProviderFallback :one
INSERT INTO provider_fallbacks (user_id, provider_id, priority, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider_id, priority, enabled, created_at
`

type CreateProviderFallbackParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ProviderID uuid.UUID `json:"provider_id"`
	Priority   int32     `json:"priority"`
	Enabled    bool      `json:"enabled"`
}

func (q *Queries) CreateProviderFallback(ctx context.Context, arg CreateProviderFallbackParams) (ProviderFallback, error) {
	row := q.db.QueryRow(ctx, createProviderFallback,
		arg.UserID,
		arg.ProviderID,
		arg.Priority,
		arg.Enabled,
	)
	var i ProviderFallback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProviderFallback = `-- name: DeleteProviderFallback :exec
DELETE FROM provider_fallbacks WHERE id = $1
`

func (q *Queries) DeleteProviderFallback(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProviderFallback, id)
	return err
}

const deleteProviderFallbacksByUserID = `-- name: DeleteProviderFallbacksByUserID :exec
DELETE FROM provider_fallbacks WHERE user_id = $1
`

func (q *Queries) DeleteProviderFallbacksByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProviderFallbacksByUserID, userID)
	return err
}

const listAllProviderFallbacksByUserID = `-- name: ListAllProviderFallbacksByUserID :many
SELECT pf.id, pf.user_id, pf.provider_id, pf.priority, pf.enabled, pf.created_at, ep.name AS provider_name, ep.provider_type
FROM provider_fallbacks pf
JOIN esp_providers ep ON ep.id = pf.provider_id
WHERE pf.user_id = $1
ORDER BY pf.priority ASC
`

type ListAllProviderFallbacksByUserIDRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ProviderID   uuid.UUID          `json:"provider_id"`
	Priority     int32              `json:"priority"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProviderName string             `json:"provider_name"`
	ProviderType ProviderType       `json:"provider_type"`
}

func (q *Queries) ListAllProviderFallbacksByUserID(ctx context.Context, userID uuid.UUID) ([]ListAllProviderFallbacksByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listAllProviderFallbacksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProviderFallbacksByUserIDRow
	for rows.Next() {
		var i ListAllProviderFallbacksByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderID,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.ProviderName,
			&i.ProviderType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderFallbacksByUserID = `-- name: ListProviderFallbacksByUserID :many
SELECT pf.id, pf.user_id, pf.provider_id, pf.priority, pf.enabled, pf.created_at, ep.name AS provider_name, ep.provider_type
FROM provider_fallbacks pf
JOIN esp_providers ep ON ep.id = pf.provider_id
WHERE pf.user_id = $1 AND pf.enabled = true
ORDER BY pf.priority ASC
`

type ListProviderFallbacksByUserIDRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ProviderID   uuid.UUID          `json:"provider_id"`
	Priority     int32              `json:"priority"`
	Enabled      bool               `json:"enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProviderName string             `json:"provider_name"`
	ProviderType ProviderType       `json:"provider_type"`
}

func (q *Queries) ListProviderFallbacksByUserID(ctx context.Context, userID uuid.UUID) ([]ListProviderFallbacksByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listProviderFallbacksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderFallbacksByUserIDRow
	for rows.Next() {
		var i ListProviderFallbacksByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderID,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.ProviderName,
			&i.ProviderType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderFallback = `-- name: UpdateProviderFallback :one
UPDATE provider_fallbacks
SET priority = $2, enabled = $3
WHERE id = $1
RETURNING id, user_id, provider_id, priority, enabled, created_at
`

type UpdateProviderFallbackParams struct {
	ID       uuid.UUID `json:"id"`
	Priority int32     `json:"priority"`
	Enabled  bool      `json:"enabled"`
}

func (q *Queries) UpdateProviderFallback(ctx context.Context, arg UpdateProviderFallbackParams) (ProviderFallback, error) {
	row := q.db.QueryRow(ctx, updateProviderFallback, arg.ID, arg.Priority, arg.Enabled)
	var i ProviderFallback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
