// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: providers.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO esp_providers (account_id, name, provider_type, api_key, smtp_config, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, name, provider_type, api_key, smtp_config, enabled, created_at, updated_at, tenant_id
`

type CreateProviderParams struct {
	AccountID    uuid.UUID      `json:"account_id"`
	Name         string         `json:"name"`
	ProviderType ProviderType   `json:"provider_type"`
	ApiKey       sql.NullString `json:"api_key"`
	SmtpConfig   []byte         `json:"smtp_config"`
	Enabled      bool           `json:"enabled"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (EspProvider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.AccountID,
		arg.Name,
		arg.ProviderType,
		arg.ApiKey,
		arg.SmtpConfig,
		arg.Enabled,
	)
	var i EspProvider
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.ProviderType,
		&i.ApiKey,
		&i.SmtpConfig,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM esp_providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, account_id, name, provider_type, api_key, smtp_config, enabled, created_at, updated_at, tenant_id FROM esp_providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (EspProvider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i EspProvider
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.ProviderType,
		&i.ApiKey,
		&i.SmtpConfig,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listProvidersByAccountID = `-- name: ListProvidersByAccountID :many
SELECT id, account_id, name, provider_type, api_key, smtp_config, enabled, created_at, updated_at, tenant_id FROM esp_providers WHERE account_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProvidersByAccountID(ctx context.Context, accountID uuid.UUID) ([]EspProvider, error) {
	rows, err := q.db.Query(ctx, listProvidersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EspProvider
	for rows.Next() {
		var i EspProvider
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.ProviderType,
			&i.ApiKey,
			&i.SmtpConfig,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE esp_providers
SET name = $2, provider_type = $3, api_key = $4, smtp_config = $5, enabled = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, name, provider_type, api_key, smtp_config, enabled, created_at, updated_at, tenant_id
`

type UpdateProviderParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	ProviderType ProviderType   `json:"provider_type"`
	ApiKey       sql.NullString `json:"api_key"`
	SmtpConfig   []byte         `json:"smtp_config"`
	Enabled      bool           `json:"enabled"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (EspProvider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.ApiKey,
		arg.SmtpConfig,
		arg.Enabled,
	)
	var i EspProvider
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.ProviderType,
		&i.ApiKey,
		&i.SmtpConfig,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
