// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"context"
	"database/sql"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AverageDeliveryDuration(ctx context.Context, arg AverageDeliveryDurationParams) ([]AverageDeliveryDurationRow, error)
	CountAPIKeysByUserID(ctx context.Context, userID uuid.UUID) (int32, error)
	CountAllDeliveryLogsByDateRange(ctx context.Context, arg CountAllDeliveryLogsByDateRangeParams) ([]CountAllDeliveryLogsByDateRangeRow, error)
	CountDeliveryLogsByGroup(ctx context.Context, arg CountDeliveryLogsByGroupParams) ([]CountDeliveryLogsByGroupRow, error)
	CountDeliveryLogsByGroupDateRange(ctx context.Context, arg CountDeliveryLogsByGroupDateRangeParams) ([]CountDeliveryLogsByGroupDateRangeRow, error)
	CountDeliveryLogsByGroupIDs(ctx context.Context, arg CountDeliveryLogsByGroupIDsParams) ([]CountDeliveryLogsByGroupIDsRow, error)
	CountDeliveryLogsByProvider(ctx context.Context, arg CountDeliveryLogsByProviderParams) ([]CountDeliveryLogsByProviderRow, error)
	CountDeliveryLogsByStatus(ctx context.Context, arg CountDeliveryLogsByStatusParams) ([]CountDeliveryLogsByStatusRow, error)
	CountGroupOwners(ctx context.Context, groupID uuid.UUID) (int64, error)
	CountMessagesByGroup(ctx context.Context, groupID pgtype.UUID) (int32, error)
	CountMessagesByGroupAndStatus(ctx context.Context, arg CountMessagesByGroupAndStatusParams) (int32, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateDeliveryLog(ctx context.Context, arg CreateDeliveryLogParams) (DeliveryLog, error)
	CreateDomainRateLimit(ctx context.Context, arg CreateDomainRateLimitParams) (DomainRateLimit, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (EspProvider, error)
	CreateProviderFallback(ctx context.Context, arg CreateProviderFallbackParams) (ProviderFallback, error)
	CreateRoutingRule(ctx context.Context, arg CreateRoutingRuleParams) (RoutingRule, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DailyDeliveryCountsAll(ctx context.Context, arg DailyDeliveryCountsAllParams) ([]DailyDeliveryCountsAllRow, error)
	DailyDeliveryCountsByGroup(ctx context.Context, arg DailyDeliveryCountsByGroupParams) ([]DailyDeliveryCountsByGroupRow, error)
	DailyDeliveryCountsByGroupIDs(ctx context.Context, arg DailyDeliveryCountsByGroupIDsParams) ([]DailyDeliveryCountsByGroupIDsRow, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteAllAPIKeysByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteDomainRateLimit(ctx context.Context, id uuid.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteGroupMember(ctx context.Context, id uuid.UUID) error
	DeleteGroupMembersByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteProvider(ctx context.Context, id uuid.UUID) error
	DeleteProviderFallback(ctx context.Context, id uuid.UUID) error
	DeleteProviderFallbacksByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteRoutingRule(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeliveryCountsByGroupAll(ctx context.Context, arg DeliveryCountsByGroupAllParams) ([]DeliveryCountsByGroupAllRow, error)
	DeliveryCountsByGroupAndProvider(ctx context.Context, arg DeliveryCountsByGroupAndProviderParams) ([]DeliveryCountsByGroupAndProviderRow, error)
	DeliveryCountsByGroupAndUser(ctx context.Context, arg DeliveryCountsByGroupAndUserParams) ([]DeliveryCountsByGroupAndUserRow, error)
	DeliveryCountsByProviderAll(ctx context.Context, arg DeliveryCountsByProviderAllParams) ([]DeliveryCountsByProviderAllRow, error)
	DeliveryCountsByProviderAndGroupIDs(ctx context.Context, arg DeliveryCountsByProviderAndGroupIDsParams) ([]DeliveryCountsByProviderAndGroupIDsRow, error)
	DeliveryCountsByUserAll(ctx context.Context, arg DeliveryCountsByUserAllParams) ([]DeliveryCountsByUserAllRow, error)
	DeliveryCountsByUserAndGroupIDs(ctx context.Context, arg DeliveryCountsByUserAndGroupIDsParams) ([]DeliveryCountsByUserAndGroupIDsRow, error)
	EnqueueMessage(ctx context.Context, arg EnqueueMessageParams) (Message, error)
	EnqueueMessageMetadata(ctx context.Context, arg EnqueueMessageMetadataParams) (Message, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetActivityLogByID(ctx context.Context, id uuid.UUID) (ActivityLog, error)
	GetDeliveryLogByMessageID(ctx context.Context, messageID uuid.UUID) (DeliveryLog, error)
	GetDeliveryLogByProviderMessageID(ctx context.Context, providerMessageID sql.NullString) (DeliveryLog, error)
	GetDomainRateLimit(ctx context.Context, arg GetDomainRateLimitParams) (DomainRateLimit, error)
	GetGlobalStdoutProvider(ctx context.Context) (EspProvider, error)
	GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupByName(ctx context.Context, name string) (Group, error)
	GetGroupMemberByID(ctx context.Context, id uuid.UUID) (GroupMember, error)
	GetGroupMemberByUserAndGroup(ctx context.Context, arg GetGroupMemberByUserAndGroupParams) (GroupMember, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetProviderByID(ctx context.Context, id uuid.UUID) (EspProvider, error)
	GetQueuedMessages(ctx context.Context, limit int32) ([]Message, error)
	GetRoutingRuleByID(ctx context.Context, id uuid.UUID) (RoutingRule, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetStdoutProviderByGroupID(ctx context.Context, groupID uuid.UUID) (EspProvider, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username sql.NullString) (User, error)
	GetUserByUsernameAndGroupID(ctx context.Context, arg GetUserByUsernameAndGroupIDParams) (User, error)
	GrantProviderAccess(ctx context.Context, arg GrantProviderAccessParams) error
	IncrementFailedAttempts(ctx context.Context, id uuid.UUID) error
	IncrementMonthlySent(ctx context.Context, id uuid.UUID) error
	IncrementRetryCount(ctx context.Context, arg IncrementRetryCountParams) error
	IsProviderAccessible(ctx context.Context, arg IsProviderAccessibleParams) (bool, error)
	ListAPIKeysByUserID(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysByUserIDRow, error)
	ListAccessibleProviders(ctx context.Context, groupID uuid.UUID) ([]EspProvider, error)
	ListActivityLogsByActorID(ctx context.Context, arg ListActivityLogsByActorIDParams) ([]ActivityLog, error)
	ListActivityLogsByGroupID(ctx context.Context, arg ListActivityLogsByGroupIDParams) ([]ActivityLog, error)
	ListActivityLogsByResource(ctx context.Context, arg ListActivityLogsByResourceParams) ([]ActivityLog, error)
	ListAllProviderFallbacksByUserID(ctx context.Context, userID uuid.UUID) ([]ListAllProviderFallbacksByUserIDRow, error)
	ListDeletedUsers(ctx context.Context) ([]User, error)
	ListDeliveryLogsByGroupAndStatus(ctx context.Context, arg ListDeliveryLogsByGroupAndStatusParams) ([]DeliveryLog, error)
	ListDeliveryLogsByMessageID(ctx context.Context, messageID uuid.UUID) ([]DeliveryLog, error)
	ListDomainRateLimitsByGroupID(ctx context.Context, groupID uuid.UUID) ([]DomainRateLimit, error)
	ListGroupMembersByGroupID(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListGroupsByUserID(ctx context.Context, userID uuid.UUID) ([]Group, error)
	ListMembershipsByUserID(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserIDRow, error)
	ListMessagesByGroupAndStatusPaginated(ctx context.Context, arg ListMessagesByGroupAndStatusPaginatedParams) ([]Message, error)
	ListMessagesByGroupID(ctx context.Context, arg ListMessagesByGroupIDParams) ([]Message, error)
	ListMessagesByGroupPaginated(ctx context.Context, arg ListMessagesByGroupPaginatedParams) ([]Message, error)
	ListProviderAccess(ctx context.Context, providerID uuid.UUID) ([]ProviderGroupAccess, error)
	ListProviderFallbacksByUserID(ctx context.Context, userID uuid.UUID) ([]ListProviderFallbacksByUserIDRow, error)
	ListProvidersByGroupID(ctx context.Context, groupID uuid.UUID) ([]EspProvider, error)
	ListRoutingRulesByGroupID(ctx context.Context, groupID uuid.UUID) ([]RoutingRule, error)
	ListSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByGroupID(ctx context.Context, groupID uuid.UUID) ([]User, error)
	ListUsersByProviderID(ctx context.Context, providerID pgtype.UUID) ([]ListUsersByProviderIDRow, error)
	PurgeDeletedUsers(ctx context.Context) error
	ResetFailedAttempts(ctx context.Context, id uuid.UUID) error
	ResetMonthlySent(ctx context.Context, id uuid.UUID) error
	// Returns active SMTP service accounts whose anonymous_allowed_cidrs contain
	// the given source IP. Used when an unauthenticated client submits MAIL FROM.
	// Multiple matches indicate operator misconfiguration (overlapping CIDRs);
	// callers should reject the session rather than picking arbitrarily.
	ResolveAnonymousSMTPByIP(ctx context.Context, dollar_1 netip.Addr) ([]User, error)
	RestoreUser(ctx context.Context, id uuid.UUID) (User, error)
	RevokeProviderAccess(ctx context.Context, arg RevokeProviderAccessParams) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateAPIKeyStatus(ctx context.Context, arg UpdateAPIKeyStatusParams) (ApiKey, error)
	UpdateDeliveryLogStatus(ctx context.Context, arg UpdateDeliveryLogStatusParams) error
	UpdateDomainRateLimit(ctx context.Context, arg UpdateDomainRateLimitParams) (DomainRateLimit, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) (GroupMember, error)
	UpdateGroupStatus(ctx context.Context, arg UpdateGroupStatusParams) (Group, error)
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
	UpdatePasswordDisabled(ctx context.Context, arg UpdatePasswordDisabledParams) (User, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (EspProvider, error)
	UpdateProviderFallback(ctx context.Context, arg UpdateProviderFallbackParams) (ProviderFallback, error)
	UpdateRoutingRule(ctx context.Context, arg UpdateRoutingRuleParams) (RoutingRule, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAnonymous(ctx context.Context, arg UpdateUserAnonymousParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
