// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDeliveryLog(ctx context.Context, arg CreateDeliveryLogParams) (DeliveryLog, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (EspProvider, error)
	CreateRoutingRule(ctx context.Context, arg CreateRoutingRuleParams) (RoutingRule, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DeleteProvider(ctx context.Context, id uuid.UUID) error
	DeleteRoutingRule(ctx context.Context, id uuid.UUID) error
	EnqueueMessage(ctx context.Context, arg EnqueueMessageParams) (Message, error)
	GetAccountByAPIKey(ctx context.Context, apiKey string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByName(ctx context.Context, name string) (Account, error)
	GetDeliveryLogByMessageID(ctx context.Context, messageID uuid.UUID) (DeliveryLog, error)
	GetDeliveryLogByProviderMessageID(ctx context.Context, providerMessageID sql.NullString) (DeliveryLog, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetProviderByID(ctx context.Context, id uuid.UUID) (EspProvider, error)
	GetQueuedMessages(ctx context.Context, limit int32) ([]Message, error)
	GetRoutingRuleByID(ctx context.Context, id uuid.UUID) (RoutingRule, error)
	IncrementRetryCount(ctx context.Context, arg IncrementRetryCountParams) error
	ListAccounts(ctx context.Context) ([]Account, error)
	ListDeliveryLogsByMessageID(ctx context.Context, messageID uuid.UUID) ([]DeliveryLog, error)
	ListDeliveryLogsByTenantAndStatus(ctx context.Context, arg ListDeliveryLogsByTenantAndStatusParams) ([]DeliveryLog, error)
	ListMessagesByAccountID(ctx context.Context, arg ListMessagesByAccountIDParams) ([]Message, error)
	ListProvidersByAccountID(ctx context.Context, accountID uuid.UUID) ([]EspProvider, error)
	ListRoutingRulesByAccountID(ctx context.Context, accountID uuid.UUID) ([]RoutingRule, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateDeliveryLogStatus(ctx context.Context, arg UpdateDeliveryLogStatusParams) error
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (EspProvider, error)
	UpdateRoutingRule(ctx context.Context, arg UpdateRoutingRuleParams) (RoutingRule, error)
}

var _ Querier = (*Queries)(nil)
