// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing_rules.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createRoutingRule = `-- name: CreateRoutingRule :one
INSERT INTO routing_rules (group_id, priority, conditions, provider_id, enabled)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, priority, conditions, provider_id, enabled, created_at, updated_at, group_id
`

type CreateRoutingRuleParams struct {
	GroupID    uuid.UUID `json:"group_id"`
	Priority   int32     `json:"priority"`
	Conditions []byte    `json:"conditions"`
	ProviderID uuid.UUID `json:"provider_id"`
	Enabled    bool      `json:"enabled"`
}

func (q *Queries) CreateRoutingRule(ctx context.Context, arg CreateRoutingRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, createRoutingRule,
		arg.GroupID,
		arg.Priority,
		arg.Conditions,
		arg.ProviderID,
		arg.Enabled,
	)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Conditions,
		&i.ProviderID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const deleteRoutingRule = `-- name: DeleteRoutingRule :exec
DELETE FROM routing_rules WHERE id = $1
`

func (q *Queries) DeleteRoutingRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoutingRule, id)
	return err
}

const getRoutingRuleByID = `-- name: GetRoutingRuleByID :one
SELECT id, priority, conditions, provider_id, enabled, created_at, updated_at, group_id FROM routing_rules WHERE id = $1
`

func (q *Queries) GetRoutingRuleByID(ctx context.Context, id uuid.UUID) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, getRoutingRuleByID, id)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Conditions,
		&i.ProviderID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const listRoutingRulesByGroupID = `-- name: ListRoutingRulesByGroupID :many
SELECT id, priority, conditions, provider_id, enabled, created_at, updated_at, group_id FROM routing_rules WHERE group_id = $1 ORDER BY priority ASC
`

func (q *Queries) ListRoutingRulesByGroupID(ctx context.Context, groupID uuid.UUID) ([]RoutingRule, error) {
	rows, err := q.db.Query(ctx, listRoutingRulesByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutingRule
	for rows.Next() {
		var i RoutingRule
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.Conditions,
			&i.ProviderID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoutingRule = `-- name: UpdateRoutingRule :one
UPDATE routing_rules
SET priority = $2, conditions = $3, provider_id = $4, enabled = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, priority, conditions, provider_id, enabled, created_at, updated_at, group_id
`

type UpdateRoutingRuleParams struct {
	ID         uuid.UUID `json:"id"`
	Priority   int32     `json:"priority"`
	Conditions []byte    `json:"conditions"`
	ProviderID uuid.UUID `json:"provider_id"`
	Enabled    bool      `json:"enabled"`
}

func (q *Queries) UpdateRoutingRule(ctx context.Context, arg UpdateRoutingRuleParams) (RoutingRule, error) {
	row := q.db.QueryRow(ctx, updateRoutingRule,
		arg.ID,
		arg.Priority,
		arg.Conditions,
		arg.ProviderID,
		arg.Enabled,
	)
	var i RoutingRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Conditions,
		&i.ProviderID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}
