// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Tenant represents a row in the tenants table.
type Tenant struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	MonthlyLimit int32              `json:"monthly_limit"`
	MonthlySent  int32              `json:"monthly_sent"`
	AllowedIPs   []string           `json:"allowed_ips"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, status, monthly_limit)
VALUES ($1, 'active', $2)
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at
`

type CreateTenantParams struct {
	Name         string `json:"name"`
	MonthlyLimit int32  `json:"monthly_limit"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.MonthlyLimit)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIPs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIPs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at FROM tenants WHERE name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIPs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2, status = $3, monthly_limit = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at
`

type UpdateTenantParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Status       string    `json:"status"`
	MonthlyLimit int32     `json:"monthly_limit"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.ID, arg.Name, arg.Status, arg.MonthlyLimit)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.MonthlyLimit,
		&i.MonthlySent,
		&i.AllowedIPs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, status, monthly_limit, monthly_sent, allowed_ips, created_at, updated_at FROM tenants ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.MonthlyLimit,
			&i.MonthlySent,
			&i.AllowedIPs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementMonthlySent = `-- name: IncrementMonthlySent :exec
UPDATE tenants
SET monthly_sent = monthly_sent + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementMonthlySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMonthlySent, id)
	return err
}

const resetMonthlySent = `-- name: ResetMonthlySent :exec
UPDATE tenants
SET monthly_sent = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetMonthlySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetMonthlySent, id)
	return err
}
