// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, account_type, username, api_key, allowed_domains)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains
`

type CreateUserParams struct {
	Email          string         `json:"email"`
	PasswordHash   string         `json:"password_hash"`
	AccountType    string         `json:"account_type"`
	Username       sql.NullString `json:"username"`
	ApiKey         sql.NullString `json:"api_key"`
	AllowedDomains []byte         `json:"allowed_domains"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.AccountType,
		arg.Username,
		arg.ApiKey,
		arg.AllowedDomains,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains FROM users WHERE api_key = $1
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :exec
UPDATE users
SET failed_attempts = failed_attempts + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedAttempts, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.ApiKey,
			&i.AllowedDomains,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_attempts = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, status = $3, allowed_domains = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains
`

type UpdateUserParams struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	Status         string    `json:"status"`
	AllowedDomains []byte    `json:"allowed_domains"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Status,
		arg.AllowedDomains,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW(), failed_attempts = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
	)
	return i, err
}
