// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package storage

import (
	"context"
	"database/sql"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, account_type, username, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

type CreateUserParams struct {
	Email            string         `json:"email"`
	PasswordHash     string         `json:"password_hash"`
	AccountType      string         `json:"account_type"`
	Username         sql.NullString `json:"username"`
	AllowedDomains   []byte         `json:"allowed_domains"`
	PasswordDisabled bool           `json:"password_disabled"`
	ProviderID       pgtype.UUID    `json:"provider_id"`
	HomeGroupID      pgtype.UUID    `json:"home_group_id"`
	DisplayName      sql.NullString `json:"display_name"`
	Description      pgtype.Text    `json:"description"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.AccountType,
		arg.Username,
		arg.AllowedDomains,
		arg.PasswordDisabled,
		arg.ProviderID,
		arg.HomeGroupID,
		arg.DisplayName,
		arg.Description,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const getUserByUsernameAndGroupID = `-- name: GetUserByUsernameAndGroupID :one
SELECT u.id, u.email, u.password_hash, u.status, u.failed_attempts, u.last_login, u.created_at, u.updated_at, u.username, u.account_type, u.allowed_domains, u.password_disabled, u.provider_id, u.home_group_id, u.display_name, u.description, u.deleted_at, u.anonymous_allowed, u.anonymous_allowed_cidrs FROM users u
JOIN groups g ON u.home_group_id = g.id
WHERE u.username = $1 AND g.id = $2
AND u.account_type = 'smtp'
AND u.deleted_at IS NULL
`

type GetUserByUsernameAndGroupIDParams struct {
	Username sql.NullString `json:"username"`
	ID       uuid.UUID      `json:"id"`
}

func (q *Queries) GetUserByUsernameAndGroupID(ctx context.Context, arg GetUserByUsernameAndGroupIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameAndGroupID, arg.Username, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :exec
UPDATE users
SET failed_attempts = failed_attempts + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedAttempts, id)
	return err
}

const listDeletedUsers = `-- name: ListDeletedUsers :many
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs FROM users WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listDeletedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.AllowedDomains,
			&i.PasswordDisabled,
			&i.ProviderID,
			&i.HomeGroupID,
			&i.DisplayName,
			&i.Description,
			&i.DeletedAt,
			&i.AnonymousAllowed,
			&i.AnonymousAllowedCidrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs FROM users WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.AllowedDomains,
			&i.PasswordDisabled,
			&i.ProviderID,
			&i.HomeGroupID,
			&i.DisplayName,
			&i.Description,
			&i.DeletedAt,
			&i.AnonymousAllowed,
			&i.AnonymousAllowedCidrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByGroupID = `-- name: ListUsersByGroupID :many
SELECT u.id, u.email, u.password_hash, u.status, u.failed_attempts, u.last_login, u.created_at, u.updated_at, u.username, u.account_type, u.allowed_domains, u.password_disabled, u.provider_id, u.home_group_id, u.display_name, u.description, u.deleted_at, u.anonymous_allowed, u.anonymous_allowed_cidrs FROM users u
JOIN group_members gm ON u.id = gm.user_id
WHERE gm.group_id = $1 AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
`

func (q *Queries) ListUsersByGroupID(ctx context.Context, groupID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.AllowedDomains,
			&i.PasswordDisabled,
			&i.ProviderID,
			&i.HomeGroupID,
			&i.DisplayName,
			&i.Description,
			&i.DeletedAt,
			&i.AnonymousAllowed,
			&i.AnonymousAllowedCidrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByProviderID = `-- name: ListUsersByProviderID :many
SELECT u.id, u.email, u.account_type, gm.role, g.id AS group_id, g.name AS group_name
FROM users u
JOIN group_members gm ON u.id = gm.user_id
JOIN groups g ON gm.group_id = g.id
WHERE u.provider_id = $1 AND u.deleted_at IS NULL
ORDER BY g.name, u.email
`

type ListUsersByProviderIDRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	AccountType string    `json:"account_type"`
	Role        string    `json:"role"`
	GroupID     uuid.UUID `json:"group_id"`
	GroupName   string    `json:"group_name"`
}

func (q *Queries) ListUsersByProviderID(ctx context.Context, providerID pgtype.UUID) ([]ListUsersByProviderIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByProviderID, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByProviderIDRow
	for rows.Next() {
		var i ListUsersByProviderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AccountType,
			&i.Role,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeletedUsers = `-- name: PurgeDeletedUsers :exec
DELETE FROM users WHERE deleted_at IS NOT NULL AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PurgeDeletedUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeDeletedUsers)
	return err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_attempts = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, id)
	return err
}

const resolveAnonymousSMTPByIP = `-- name: ResolveAnonymousSMTPByIP :many
SELECT u.id, u.email, u.password_hash, u.status, u.failed_attempts, u.last_login, u.created_at, u.updated_at, u.username, u.account_type, u.allowed_domains, u.password_disabled, u.provider_id, u.home_group_id, u.display_name, u.description, u.deleted_at, u.anonymous_allowed, u.anonymous_allowed_cidrs
FROM users u
JOIN groups g ON u.home_group_id = g.id
WHERE u.account_type = 'smtp'
  AND u.status = 'active'
  AND u.anonymous_allowed = true
  AND u.deleted_at IS NULL
  AND g.status = 'active'
  AND EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(u.anonymous_allowed_cidrs) AS c(cidr)
      WHERE $1::inet <<= c.cidr::inet
  )
`

// Returns active SMTP service accounts whose anonymous_allowed_cidrs contain
// the given source IP. Used when an unauthenticated client submits MAIL FROM.
// Multiple matches indicate operator misconfiguration (overlapping CIDRs);
// callers should reject the session rather than picking arbitrarily.
func (q *Queries) ResolveAnonymousSMTPByIP(ctx context.Context, dollar_1 netip.Addr) ([]User, error) {
	rows, err := q.db.Query(ctx, resolveAnonymousSMTPByIP, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.AllowedDomains,
			&i.PasswordDisabled,
			&i.ProviderID,
			&i.HomeGroupID,
			&i.DisplayName,
			&i.Description,
			&i.DeletedAt,
			&i.AnonymousAllowed,
			&i.AnonymousAllowedCidrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET deleted_at = NULL, status = 'active', updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = NOW(), status = 'deleted', updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const updatePasswordDisabled = `-- name: UpdatePasswordDisabled :one
UPDATE users
SET password_disabled = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

type UpdatePasswordDisabledParams struct {
	ID               uuid.UUID `json:"id"`
	PasswordDisabled bool      `json:"password_disabled"`
}

func (q *Queries) UpdatePasswordDisabled(ctx context.Context, arg UpdatePasswordDisabledParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePasswordDisabled, arg.ID, arg.PasswordDisabled)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, status = $3, allowed_domains = $4, display_name = $5, description = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

type UpdateUserParams struct {
	ID             uuid.UUID      `json:"id"`
	Email          string         `json:"email"`
	Status         string         `json:"status"`
	AllowedDomains []byte         `json:"allowed_domains"`
	DisplayName    sql.NullString `json:"display_name"`
	Description    pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Status,
		arg.AllowedDomains,
		arg.DisplayName,
		arg.Description,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const updateUserAnonymous = `-- name: UpdateUserAnonymous :one
UPDATE users
SET anonymous_allowed = $2,
    anonymous_allowed_cidrs = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

type UpdateUserAnonymousParams struct {
	ID                    uuid.UUID `json:"id"`
	AnonymousAllowed      bool      `json:"anonymous_allowed"`
	AnonymousAllowedCidrs []byte    `json:"anonymous_allowed_cidrs"`
}

func (q *Queries) UpdateUserAnonymous(ctx context.Context, arg UpdateUserAnonymousParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAnonymous, arg.ID, arg.AnonymousAllowed, arg.AnonymousAllowedCidrs)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW(), failed_attempts = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProvider = `-- name: UpdateUserProvider :one
UPDATE users
SET provider_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

type UpdateUserProviderParams struct {
	ID         uuid.UUID   `json:"id"`
	ProviderID pgtype.UUID `json:"provider_id"`
}

func (q *Queries) UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProvider, arg.ID, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at, anonymous_allowed, anonymous_allowed_cidrs
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
		&i.AnonymousAllowed,
		&i.AnonymousAllowedCidrs,
	)
	return i, err
}
