// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, account_type, username, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

type CreateUserParams struct {
	Email            string         `json:"email"`
	PasswordHash     string         `json:"password_hash"`
	AccountType      string         `json:"account_type"`
	Username         sql.NullString `json:"username"`
	ApiKey           sql.NullString `json:"api_key"`
	AllowedDomains   []byte         `json:"allowed_domains"`
	PasswordDisabled bool           `json:"password_disabled"`
	ProviderID       pgtype.UUID    `json:"provider_id"`
	HomeGroupID      pgtype.UUID    `json:"home_group_id"`
	DisplayName      sql.NullString `json:"display_name"`
	Description      pgtype.Text    `json:"description"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.AccountType,
		arg.Username,
		arg.ApiKey,
		arg.AllowedDomains,
		arg.PasswordDisabled,
		arg.ProviderID,
		arg.HomeGroupID,
		arg.DisplayName,
		arg.Description,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at FROM users WHERE api_key = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at FROM users WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsernameAndGroupKey = `-- name: GetUserByUsernameAndGroupKey :one
SELECT u.id, u.email, u.password_hash, u.status, u.failed_attempts, u.last_login, u.created_at, u.updated_at, u.username, u.account_type, u.api_key, u.allowed_domains, u.password_disabled, u.provider_id, u.home_group_id, u.display_name, u.description, u.deleted_at FROM users u
JOIN groups g ON u.home_group_id = g.id
WHERE u.username = $1 AND g.group_key = $2
AND u.deleted_at IS NULL
`

type GetUserByUsernameAndGroupKeyParams struct {
	Username sql.NullString `json:"username"`
	GroupKey uuid.UUID      `json:"group_key"`
}

func (q *Queries) GetUserByUsernameAndGroupKey(ctx context.Context, arg GetUserByUsernameAndGroupKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameAndGroupKey, arg.Username, arg.GroupKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :exec
UPDATE users
SET failed_attempts = failed_attempts + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedAttempts, id)
	return err
}

const listDeletedUsers = `-- name: ListDeletedUsers :many
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at FROM users WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listDeletedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.ApiKey,
			&i.AllowedDomains,
			&i.PasswordDisabled,
			&i.ProviderID,
			&i.HomeGroupID,
			&i.DisplayName,
			&i.Description,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at FROM users WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.ApiKey,
			&i.AllowedDomains,
			&i.PasswordDisabled,
			&i.ProviderID,
			&i.HomeGroupID,
			&i.DisplayName,
			&i.Description,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByGroupID = `-- name: ListUsersByGroupID :many
SELECT u.id, u.email, u.password_hash, u.status, u.failed_attempts, u.last_login, u.created_at, u.updated_at, u.username, u.account_type, u.api_key, u.allowed_domains, u.password_disabled, u.provider_id, u.home_group_id, u.display_name, u.description, u.deleted_at FROM users u
JOIN group_members gm ON u.id = gm.user_id
WHERE gm.group_id = $1 AND u.deleted_at IS NULL
ORDER BY u.created_at DESC
`

func (q *Queries) ListUsersByGroupID(ctx context.Context, groupID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.FailedAttempts,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AccountType,
			&i.ApiKey,
			&i.AllowedDomains,
			&i.PasswordDisabled,
			&i.ProviderID,
			&i.HomeGroupID,
			&i.DisplayName,
			&i.Description,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByProviderID = `-- name: ListUsersByProviderID :many
SELECT u.id, u.email, u.account_type, gm.role, g.id AS group_id, g.name AS group_name
FROM users u
JOIN group_members gm ON u.id = gm.user_id
JOIN groups g ON gm.group_id = g.id
WHERE u.provider_id = $1 AND u.deleted_at IS NULL
ORDER BY g.name, u.email
`

type ListUsersByProviderIDRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	AccountType string    `json:"account_type"`
	Role        string    `json:"role"`
	GroupID     uuid.UUID `json:"group_id"`
	GroupName   string    `json:"group_name"`
}

func (q *Queries) ListUsersByProviderID(ctx context.Context, providerID pgtype.UUID) ([]ListUsersByProviderIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByProviderID, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByProviderIDRow
	for rows.Next() {
		var i ListUsersByProviderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AccountType,
			&i.Role,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeletedUsers = `-- name: PurgeDeletedUsers :exec
DELETE FROM users WHERE deleted_at IS NOT NULL AND deleted_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) PurgeDeletedUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeDeletedUsers)
	return err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_attempts = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, id)
	return err
}

const resetUserAPIKey = `-- name: ResetUserAPIKey :one
UPDATE users
SET api_key = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

type ResetUserAPIKeyParams struct {
	ID     uuid.UUID      `json:"id"`
	ApiKey sql.NullString `json:"api_key"`
}

func (q *Queries) ResetUserAPIKey(ctx context.Context, arg ResetUserAPIKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, resetUserAPIKey, arg.ID, arg.ApiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET deleted_at = NULL, status = 'active', updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = NOW(), status = 'deleted', updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const updatePasswordDisabled = `-- name: UpdatePasswordDisabled :one
UPDATE users
SET password_disabled = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

type UpdatePasswordDisabledParams struct {
	ID               uuid.UUID `json:"id"`
	PasswordDisabled bool      `json:"password_disabled"`
}

func (q *Queries) UpdatePasswordDisabled(ctx context.Context, arg UpdatePasswordDisabledParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePasswordDisabled, arg.ID, arg.PasswordDisabled)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, status = $3, allowed_domains = $4, display_name = $5, description = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

type UpdateUserParams struct {
	ID             uuid.UUID      `json:"id"`
	Email          string         `json:"email"`
	Status         string         `json:"status"`
	AllowedDomains []byte         `json:"allowed_domains"`
	DisplayName    sql.NullString `json:"display_name"`
	Description    pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Status,
		arg.AllowedDomains,
		arg.DisplayName,
		arg.Description,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW(), failed_attempts = 0, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProvider = `-- name: UpdateUserProvider :one
UPDATE users
SET provider_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

type UpdateUserProviderParams struct {
	ID         uuid.UUID   `json:"id"`
	ProviderID pgtype.UUID `json:"provider_id"`
}

func (q *Queries) UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProvider, arg.ID, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, status, failed_attempts, last_login, created_at, updated_at, username, account_type, api_key, allowed_domains, password_disabled, provider_id, home_group_id, display_name, description, deleted_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.FailedAttempts,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AccountType,
		&i.ApiKey,
		&i.AllowedDomains,
		&i.PasswordDisabled,
		&i.ProviderID,
		&i.HomeGroupID,
		&i.DisplayName,
		&i.Description,
		&i.DeletedAt,
	)
	return i, err
}
